services:
  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
    depends_on:
      - ollama
    networks:
      - localnet
  ollama:
    image: ollama/ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    networks:
      - localnet
volumes:
  ollama_data:
networks:
  localnet:
    driver: bridge 